<a href="https://colab.research.google.com/github/Howl06/practice/blob/main/01_RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [ ]:
# Sample(batch) size: 1
# Sequence Length: 5
# input feature dimension: 8

inputs = tf.random.normal([1, 5, 8]) # random Tensor
inputs.shape

TensorShape([1, 5, 8])

In [ ]:
inputs

<tf.Tensor: shape=(1, 5, 8), dtype=float32, numpy=
array([[[-1.2306488 , -1.266499  , -0.20310144,  0.04074484,
         -1.4450277 ,  0.22861646, -0.6186045 , -0.02218798],
        [-2.5322807 , -0.33521456,  0.11468615, -0.23164706,
          0.13198195, -0.2140072 ,  0.25184426,  0.05546312],
        [ 0.364226  ,  1.8162379 , -1.0135052 , -1.08317   ,
         -3.3672087 ,  0.8473002 ,  1.6514212 , -0.7392855 ],
        [-0.6025208 , -1.099503  ,  0.46034715, -0.19284116,
         -1.0339054 ,  0.4242744 ,  2.0174463 , -0.9809739 ],
        [ 1.372991  , -0.29098135, -1.9368167 , -0.68479544,
         -0.52493817, -1.4007207 , -0.9138788 ,  1.0502641 ]]],
      dtype=float32)>

# tf.keras.layers.LSTM

In [ ]:
output = layers.LSTM(units=32)(inputs)
output2 = layers.LSTM(units=32, 
                      return_sequences=True)(inputs)
print(output.shape) # (batch size, feature dim)
print(output2.shape) # (batch size, seq length, feature dim)

(1, 32)
(1, 5, 32)


In [ ]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(units=32, 
                                                                    # return_sequences=True, 
                                                                    return_state=True)(inputs)

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 32) tf.Tensor(
[[-0.03646588 -0.0042519   0.2842238   0.14410956 -0.28438362 -0.04506781
   0.08206069  0.00810269  0.02712635 -0.05974983  0.13594513  0.20361061
  -0.1573083  -0.05102736 -0.02771114  0.06380498 -0.1305784   0.19235596
  -0.11034832 -0.17715406  0.049016   -0.05440481 -0.23206827  0.08538458
  -0.08764145  0.13636652  0.01165786 -0.04335005  0.09415954 -0.19173118
   0.20694484 -0.2393616 ]], shape=(1, 32), dtype=float32)
final_hiden_state (h):  (1, 32) tf.Tensor(
[[-0.03646588 -0.0042519   0.2842238   0.14410956 -0.28438362 -0.04506781
   0.08206069  0.00810269  0.02712635 -0.05974983  0.13594513  0.20361061
  -0.1573083  -0.05102736 -0.02771114  0.06380498 -0.1305784   0.19235596
  -0.11034832 -0.17715406  0.049016   -0.05440481 -0.23206827  0.08538458
  -0.08764145  0.13636652  0.01165786 -0.04335005  0.09415954 -0.19173118
   0.20694484 -0.2393616 ]], shape=(1, 32), dtype=float32)
final_cell_state (c):  (1, 32) tf.Tensor(
[[-0.07582878 -0.01

# tf.keras.layers.GRU

In [ ]:
output = layers.GRU(units=32)(inputs)
output2 = layers.GRU(units=32, 
                     return_sequences=True)(inputs)
print(output.shape)
print(output2.shape)

(1, 32)
(1, 5, 32)


In [ ]:
whole_sequence_output, final_state = layers.GRU(3, 
                                                # return_sequences=True, 
                                                return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 3) tf.Tensor([[-0.134182   -0.14745295 -0.14449257]], shape=(1, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[-0.134182   -0.14745295 -0.14449257]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [ ]:
print(inputs.shape)
output = layers.Bidirectional(layers.LSTM(3))(inputs)
print(output.shape)

(1, 5, 8)
(1, 6)


In [ ]:
# merge_mode: 'sum' or 'concat'
output = layers.Bidirectional(layers.LSTM(3), 
                              merge_mode='sum')(inputs)
print(output.shape)

(1, 3)


In [ ]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(3, 
                                          return_sequences=True))(inputs)
print(output.shape)

(1, 5, 6)


In [ ]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(3, 
                                                                                        return_sequences=True, 
                                                                                        return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 6) tf.Tensor(
[[[ 0.03061581  0.2248348   0.07931396 -0.03143562  0.18595858
    0.32031432]
  [-0.01232281 -0.03293349 -0.03188569 -0.24107176 -0.00561516
    0.07433058]
  [ 0.15194665  0.1096346  -0.1494526  -0.22596914 -0.03218351
    0.06546205]
  [ 0.24567495  0.09639515 -0.24757686 -0.03130846 -0.05523374
   -0.05407988]
  [-0.25770894  0.0063352   0.00525259 -0.01992668 -0.10565272
   -0.06472294]]], shape=(1, 5, 6), dtype=float32)
forward_h :  (1, 3) tf.Tensor([[-0.25770894  0.0063352   0.00525259]], shape=(1, 3), dtype=float32)
forward_c :  (1, 3) tf.Tensor([[-0.4901394   0.05349621  0.01219812]], shape=(1, 3), dtype=float32)
backward_h :  (1, 3) tf.Tensor([[-0.03143562  0.18595858  0.32031432]], shape=(1, 3), dtype=float32)
backward_c :  (1, 3) tf.Tensor([[-0.05759957  0.23697835  0.41579303]], shape=(1, 3), dtype=float32)


## Many-to-one

In [ ]:
input = layers.Input(shape=(50, 8)) # (seq len, feature dim)
x = layers.LSTM(32)(input)

ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 50, 8)]           0         
                                                                 
 lstm_7 (LSTM)               (None, 32)                5248      
                                                                 
 dense (Dense)               (None, 10)                330       
                                                                 
Total params: 5,578
Trainable params: 5,578
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, 
                 return_sequences=True)(input)
x2 = layers.LSTM(256, 
                 return_sequences=True)(x1)
x3 = layers.LSTM(512)(x2)

ouput = layers.Dense(10, activation='softmax')(x3)

model = models.Model(input, ouput)
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 5, 8)]            0         
                                                                 
 lstm_18 (LSTM)              (None, 5, 128)            70144     
                                                                 
 lstm_19 (LSTM)              (None, 5, 256)            394240    
                                                                 
 lstm_20 (LSTM)              (None, 512)               1574912   
                                                                 
 dense_3 (Dense)             (None, 10)                5130      
                                                                 
Total params: 2,044,426
Trainable params: 2,044,426
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [ ]:
input = layers.Input(shape=(500, 8))
x = layers.LSTM(10, 
                return_sequences=True)(input)
                
output = layers.Dense(20, activation='softmax')(x)
model = models.Model(input, output)
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 500, 8)]          0         
                                                                 
 lstm_19 (LSTM)              (None, 500, 10)           760       
                                                                 
 dense_3 (Dense)             (None, 500, 20)           220       
                                                                 
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq

In [ ]:
# Video RNN
# 10sec, 30fps, (200,200,3)
# (1, 300, 200, 200, 3): Video
# (1, 300, 1024) : video frame feature




In [ ]:
# 我要找一家餐廳吃飯

# token: 斷詞

# English: word
# The song was featured in the musical Can-Can when it was introduced

# chinese: 斷詞 斷字
# 我要找一家餐廳吃飯
# 斷詞：我, 要找, 一家, 餐廳, 吃飯
# 斷字：我, 要, 找, 一, 家, 餐, 廳, 吃, 飯

# dictionary = {
#       我: 7, 要找: 19, 一家: 200, ...
# } 5000

# 我, 要找, 一家, 餐廳, 吃飯 -> [7, 19, 200, 40, 56]  (5, )
# one-hot encoding -> (5, 5000)
# Embedding(128) -> (5, 128) 詞向量



# 斷字：我, 要, 找, 一, 家, 餐, 廳, 吃, 飯
# dictionary = {
#       我: 7, 要： 20, 找: 19, 一: 5, 家：200, ...
# } 5000
# 我, 要, 找, 一, 家, 餐, 廳, 吃, 飯 -> [7, 20, 19, 5 ,6 , 100, 229] (7, )

# BERT (Transformer) -> (7, 256)

In [ ]:
token

The song was featured in the musical Can-Can when it was introduced by the French actress Lilo.

token

The song was featured in the musical Can-Can.

Tokenize (word, character)

In [ ]:
sentence = "The song was featured in the musical Can-Can ."
sentence.split(' ')

['The', 'song', 'was', 'featured', 'in', 'the', 'musical', 'Can-Can', '.']

In [ ]:
"粉絲數超過0的網紅"
中文：詞, 字

斷詞: jieba
"粉絲, 數, 超過, 0, 的, 網紅" (6, )
"粉絲數, 超過, 0, 的, 網紅" (5, )

斷字
"粉, 絲, 數, 超, 過, 0 , 的, 網 , 紅"

[120, 130, 200, 400, 222, 40]

(1, 6)


Embedding: convert token to vector
128,

(1, 6, 128)