<a href="https://colab.research.google.com/github/Howl06/practice/blob/main/tensorflow.keras/01_RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [3]:
# Sample(batch) size: 1
# Sequence Length: 5
# input feature dimension: 8

inputs = tf.random.normal([1, 5, 8]) # random Tensor
inputs.shape

TensorShape([1, 5, 8])

In [4]:
inputs

<tf.Tensor: shape=(1, 5, 8), dtype=float32, numpy=
array([[[-3.0767317 ,  0.5672721 , -0.78390265, -1.0763227 ,
         -0.9163147 ,  1.7109067 , -1.7822211 , -0.18035157],
        [-1.0469445 , -0.7987742 , -1.1160104 ,  0.7235162 ,
         -1.0322646 ,  0.11728047,  0.7935125 , -0.47996187],
        [-0.54970545, -0.49140036,  0.1983073 , -0.34211144,
         -1.483883  ,  0.21783145,  1.3836673 ,  0.46468952],
        [-0.03108217, -1.1095904 , -0.29535437,  1.1344274 ,
         -1.1807697 , -0.4882205 , -1.4605124 ,  0.7970489 ],
        [ 0.773265  ,  0.16359007,  0.33923134,  0.27662286,
         -0.60836655,  1.0454963 ,  0.67326635, -0.6955848 ]]],
      dtype=float32)>

# tf.keras.layers.LSTM

In [5]:
output = layers.LSTM(units=32)(inputs)
# return_sequences true to many
output2 = layers.LSTM(units=32, 
                      return_sequences=True)(inputs)
print(output.shape) # (batch size, feature dim)
print(output2.shape) # (batch size, seq length, feature dim)

(1, 32)
(1, 5, 32)


In [ ]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(units=32, 
                                    return_state=True)(inputs)# return_sequences=True return Ht Ct

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 32) tf.Tensor(
[[-0.03646588 -0.0042519   0.2842238   0.14410956 -0.28438362 -0.04506781
   0.08206069  0.00810269  0.02712635 -0.05974983  0.13594513  0.20361061
  -0.1573083  -0.05102736 -0.02771114  0.06380498 -0.1305784   0.19235596
  -0.11034832 -0.17715406  0.049016   -0.05440481 -0.23206827  0.08538458
  -0.08764145  0.13636652  0.01165786 -0.04335005  0.09415954 -0.19173118
   0.20694484 -0.2393616 ]], shape=(1, 32), dtype=float32)
final_hiden_state (h):  (1, 32) tf.Tensor(
[[-0.03646588 -0.0042519   0.2842238   0.14410956 -0.28438362 -0.04506781
   0.08206069  0.00810269  0.02712635 -0.05974983  0.13594513  0.20361061
  -0.1573083  -0.05102736 -0.02771114  0.06380498 -0.1305784   0.19235596
  -0.11034832 -0.17715406  0.049016   -0.05440481 -0.23206827  0.08538458
  -0.08764145  0.13636652  0.01165786 -0.04335005  0.09415954 -0.19173118
   0.20694484 -0.2393616 ]], shape=(1, 32), dtype=float32)
final_cell_state (c):  (1, 32) tf.Tensor(
[[-0.07582878 -0.01

# tf.keras.layers.GRU

In [ ]:
output = layers.GRU(units=32)(inputs)
output2 = layers.GRU(units=32, 
                     return_sequences=True)(inputs)
print(output.shape)
print(output2.shape)

(1, 32)
(1, 5, 32)


In [6]:
whole_sequence_output, final_state = layers.GRU(units=32, 
                          # return_sequences=True, final_state = Ht
                          return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 32) tf.Tensor(
[[ 0.1706766   0.1495054   0.11176106  0.15702513 -0.26760736  0.08731748
   0.12330934  0.03417785  0.08093645  0.02190652  0.04028644 -0.10204154
   0.05543714 -0.3470062  -0.12440182 -0.16611415 -0.03901101 -0.08732677
  -0.03472112  0.09616795 -0.08615346 -0.1505644  -0.25379744 -0.2274276
  -0.00183289 -0.01647348 -0.05068874 -0.15038314 -0.23292662 -0.17472401
   0.14307755  0.00234872]], shape=(1, 32), dtype=float32)
final_state (h):  (1, 32) tf.Tensor(
[[ 0.1706766   0.1495054   0.11176106  0.15702513 -0.26760736  0.08731748
   0.12330934  0.03417785  0.08093645  0.02190652  0.04028644 -0.10204154
   0.05543714 -0.3470062  -0.12440182 -0.16611415 -0.03901101 -0.08732677
  -0.03472112  0.09616795 -0.08615346 -0.1505644  -0.25379744 -0.2274276
  -0.00183289 -0.01647348 -0.05068874 -0.15038314 -0.23292662 -0.17472401
   0.14307755  0.00234872]], shape=(1, 32), dtype=float32)


# tf.keras.layers.Bidirectional

In [8]:
print(inputs.shape)
output = layers.Bidirectional(layers.LSTM(units=32))(inputs) 
# forward_h 32 concat backward_h 32 -> output 64
print(output.shape)

(1, 5, 8)
(1, 64)


In [ ]:
# merge_mode: 'sum' or 'concat'
output = layers.Bidirectional(layers.LSTM(units=32), 
                              merge_mode='sum')(inputs)
print(output.shape)

(1, 3)


In [ ]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(3, 
                                          return_sequences=True))(inputs)
print(output.shape)

(1, 5, 6)


In [ ]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(3, 
                                                                                        return_sequences=True, 
                                                                                        return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 6) tf.Tensor(
[[[ 0.03061581  0.2248348   0.07931396 -0.03143562  0.18595858
    0.32031432]
  [-0.01232281 -0.03293349 -0.03188569 -0.24107176 -0.00561516
    0.07433058]
  [ 0.15194665  0.1096346  -0.1494526  -0.22596914 -0.03218351
    0.06546205]
  [ 0.24567495  0.09639515 -0.24757686 -0.03130846 -0.05523374
   -0.05407988]
  [-0.25770894  0.0063352   0.00525259 -0.01992668 -0.10565272
   -0.06472294]]], shape=(1, 5, 6), dtype=float32)
forward_h :  (1, 3) tf.Tensor([[-0.25770894  0.0063352   0.00525259]], shape=(1, 3), dtype=float32)
forward_c :  (1, 3) tf.Tensor([[-0.4901394   0.05349621  0.01219812]], shape=(1, 3), dtype=float32)
backward_h :  (1, 3) tf.Tensor([[-0.03143562  0.18595858  0.32031432]], shape=(1, 3), dtype=float32)
backward_c :  (1, 3) tf.Tensor([[-0.05759957  0.23697835  0.41579303]], shape=(1, 3), dtype=float32)


## Many-to-one

In [9]:
input = layers.Input(shape=(50, 8)) # (seq len, feature dim)
x = layers.LSTM(32)(input)

ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 50, 8)]           0         
                                                                 
 lstm_4 (LSTM)               (None, 32)                5248      
                                                                 
 dense (Dense)               (None, 10)                330       
                                                                 
Total params: 5,578
Trainable params: 5,578
Non-trainable params: 0
_________________________________________________________________


In [10]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, 
                 return_sequences=True)(input)
x2 = layers.LSTM(256, 
                 return_sequences=True)(x1)
x3 = layers.LSTM(512)(x2)

ouput = layers.Dense(10, activation='softmax')(x3)

model = models.Model(input, ouput)
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 5, 8)]            0         
                                                                 
 lstm_5 (LSTM)               (None, 5, 128)            70144     
                                                                 
 lstm_6 (LSTM)               (None, 5, 256)            394240    
                                                                 
 lstm_7 (LSTM)               (None, 512)               1574912   
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 2,044,426
Trainable params: 2,044,426
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [11]:
input = layers.Input(shape=(500, 8))
x = layers.LSTM(10, 
                return_sequences=True)(input)
                
output = layers.Dense(20, activation='softmax')(x)

model = models.Model(input, output)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 500, 8)]          0         
                                                                 
 lstm_8 (LSTM)               (None, 500, 10)           760       
                                                                 
 dense_2 (Dense)             (None, 500, 20)           220       
                                                                 
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq

In [ ]:
# Video RNN
# 10sec, 30fps, (200,200,3)
# (1, 300, 200, 200, 3): Video
# (1, 300, 1024) : video frame feature




In [ ]:
# 我要找一家餐廳吃飯

# token: 斷詞

# English: word
# The song was featured in the musical Can-Can when it was introduced

# chinese: 斷詞 斷字
# 我要找一家餐廳吃飯
# 斷詞：我, 要找, 一家, 餐廳, 吃飯
# 斷字：我, 要, 找, 一, 家, 餐, 廳, 吃, 飯

# dictionary = {
#       我: 7, 要找: 19, 一家: 200, ...
# } 5000

# 我, 要找, 一家, 餐廳, 吃飯 -> [7, 19, 200, 40, 56]  (5, )
# one-hot encoding -> (5, 5000)
# Embedding(128) -> (5, 128) 詞向量



# 斷字：我, 要, 找, 一, 家, 餐, 廳, 吃, 飯
# dictionary = {
#       我: 7, 要： 20, 找: 19, 一: 5, 家：200, ...
# } 5000
# 我, 要, 找, 一, 家, 餐, 廳, 吃, 飯 -> [7, 20, 19, 5 ,6 , 100, 229] (7, )

# BERT (Transformer) -> (7, 256)

In [ ]:
token

The song was featured in the musical Can-Can when it was introduced by the French actress Lilo.

token

The song was featured in the musical Can-Can.

Tokenize (word, character)

In [ ]:
sentence = "The song was featured in the musical Can-Can ."
sentence.split(' ')

['The', 'song', 'was', 'featured', 'in', 'the', 'musical', 'Can-Can', '.']

In [ ]:
"粉絲數超過0的網紅"
中文：詞, 字

斷詞: jieba
"粉絲, 數, 超過, 0, 的, 網紅" (6, )
"粉絲數, 超過, 0, 的, 網紅" (5, )

斷字
"粉, 絲, 數, 超, 過, 0 , 的, 網 , 紅"

[120, 130, 200, 400, 222, 40]

(1, 6)


Embedding: convert token to vector
128,

(1, 6, 128)